import { CalendarRange } from 'lucide-react';
import type { DashboardModuleConfig } from '../dashboard/dashboardTypes';
import { countByValue } from '../dashboard/dashboardTypes';

export const eventsModule: DashboardModuleConfig = {
  id: 'events',
  title: 'Events',
  subtitle: 'Create, edit, publish, and archive conferences, workshops, and featured events.',
  intro:
    'Keep the public event feed, featured cards, and admin records synchronized from one page.',
  route: '/dashboard/events',
  actionLabel: 'Add Event',
  searchPlaceholder: 'Search events, dates, and venues...',
  accent: 'primary',
  icon: CalendarRange,
  fields: [
    {
      key: 'title',
      label: 'Event title',
      type: 'text',
      placeholder: 'ICASD 2026 - International Research Conference',
      required: true,
      span: 2,
    },
    {
      key: 'slug',
      label: 'Slug',
      type: 'text',
      placeholder: 'icasd-2026',
      required: true,
    },
    {
      key: 'description',
      label: 'Short description',
      type: 'text',
      placeholder: 'Submit your research paper and join a leading international conference...',
      required: true,
      span: 2,
    },
    {
      key: 'type',
      label: 'Type',
      type: 'select',
      options: ['Conference', 'Workshop', 'Forum', 'Summit', 'Award'],
      placeholder: 'Select event type',
      required: true,
    },
    {
      key: 'eventDate',
      label: 'Event date',
      type: 'date',
      placeholder: 'Select event date',
      required: true,
    },
    {
      key: 'startTime',
      label: 'Start time',
      type: 'text',
      placeholder: '09:00 AM',
      required: true,
    },
    {
      key: 'location',
      label: 'Location',
      type: 'text',
      placeholder: 'Kuala Lumpur, Malaysia',
      required: true,
      span: 2,
    },
    {
      key: 'tags',
      label: 'Tags (comma-separated)',
      type: 'text',
      placeholder: 'Sustainability, Innovation',
      required: false,
    },
    {
      key: 'featured',
      label: 'Featured',
      type: 'select',
      options: ['Yes', 'No'],
      placeholder: 'Is this featured?',
      required: true,
    },
    {
      key: 'status',
      label: 'Status',
      type: 'select',
      options: ['Draft', 'Scheduled', 'Published', 'Archived'],
      placeholder: 'Select publication status',
      required: true,
    },
    {
      key: 'imageUrl',
      label: 'Event images',
      type: 'file',
      placeholder: 'Import one or more event images for the gallery',
      accept: 'image/*',
      multiple: true,
      span: 2,
    },
  ],
  columns: [
    { key: 'title', label: 'Title' },
    { key: 'eventDate', label: 'Date' },
    { key: 'location', label: 'Location' },
    { key: 'type', label: 'Type' },
    { key: 'status', label: 'Status' },
  ],
  tableTemplateColumns:
    'minmax(0, 1.45fr) minmax(0, 0.9fr) minmax(0, 1.15fr) minmax(0, 0.8fr) minmax(0, 0.85fr)',
  initialRows: [
    {
      id: '660000000000000000000001',
      values: {
        title: 'ICASD 2026 - International Research Conference',
        slug: 'icasd-2026',
        type: 'Conference',
        eventDate: '2026-05-21',
        startTime: '09:00 AM',
        location: 'Kuala Lumpur, Malaysia',
        featured: 'Yes',
        status: 'Published',
        imageUrl: ['/assets/Image/event1.jpeg', '/assets/Image/event2.jpg'],
      },
    },
    {
      id: '660000000000000000000002',
      values: {
        title: 'ICGSD 2025 - Global Academic Conference',
        slug: 'icgsd-2025',
        type: 'Conference',
        eventDate: '2025-07-22',
        startTime: '10:00 AM',
        location: 'Dubai, UAE',
        featured: 'Yes',
        status: 'Scheduled',
        imageUrl: ['/assets/Image/event3.png', '/assets/Image/event4.jpg'],
      },
    },
    {
      id: '660000000000000000000003',
      values: {
        title: 'Research Methodology Workshop',
        slug: 'research-methodology-workshop',
        type: 'Workshop',
        eventDate: '2026-08-10',
        startTime: '09:00 AM',
        location: 'Online / India',
        featured: 'No',
        status: 'Draft',
        imageUrl: ['/assets/Image/research.jpeg'],
      },
    },
  ],
  statusToneMap: {
    Draft: 'warning',
    Scheduled: 'neutral',
    Published: 'success',
    Archived: 'danger',
  },
  buildSummary: (rows) => [
    { label: 'Total events', value: String(rows.length), tone: 'neutral' },
    { label: 'Published', value: String(countByValue(rows, 'status', 'Published')), tone: 'success' },
    { label: 'Scheduled', value: String(countByValue(rows, 'status', 'Scheduled')), tone: 'warning' },
    { label: 'Featured', value: String(countByValue(rows, 'featured', 'Yes')), tone: 'neutral' },
  ],
};
